### ISSUE TITLE
Breaks undo history after file save

### ISSUE THREAD

**Issue by anghelos** [ivogabe/Brackets-Icons#98] opened 2015-10-30 15:26 UTC
After the last extension update, saving a file erases its undo cache. Probably an issue with timestamps?
Disabling Brackets-Icons fixes the problem, so it's probably the culprit.

**Comment by ivogabe** [comment] 2015-10-30 20:08
I cannot reproduce this. The latest version didn't change anything related to this. Can you check whether this is caused by a different plugin? The other plugin in combination with Brackets-Icons might cause this issue.

**Comment by anghelos** [comment] 2015-10-30 21:54
Hey,

So I checked, and you're right, it's some kind of conflict with SASSHints (
https://github.com/konstantinkobs/brackets-SASShints)

However, the issue only started appearing (on scss files) after updating to
the latest version of brackets icons.

Just wanted to let you know!

Thanks for your quick reply,

Anghelos


安国

**Comment by anghelos** [comment] 2015-10-30 23:05
After restarting my computer and installing some updates, the issue doesn't
seem to appear any more. Sorry, this might be something specific to my
machine.


安国

**Comment by petetnt** [comment] 2015-12-18 07:59
I just saw this issue and wanted to inform you that the issue is being tracked at adobe/brackets/issues/11826 and is unrelated to `Brackets-Icons`

**Comment by ivogabe** [comment] 2015-12-18 08:22
@petetnt Thanks for notifying, I'll close this one

**Closed by ivogabe** 2015-12-18 08:22 UTC
