### ISSUE TITLE
files with two extensions show both icons.

### ISSUE THREAD

**Issue by wormeyman** [ivogabe/Brackets-Icons#84] opened 2015-07-06 22:31 UTC
![image](https://cloud.githubusercontent.com/assets/1795016/8534693/a2979596-23f3-11e5-9380-5791704c5567.png)

for example the .exe.config file but if you try this with other file types it doesn't always happen for example .csv.xml looks normal but .html.js shows both icons.

**Comment by ivogabe** [comment] 2015-07-08 09:07
That's actually by design, it was introduced in the latest release. It only happens to known files, for instance .exe, .js and .html are supported extensions, but .csv not (but you can of course create a PR if you want that icon too). The alignment is a bit off at the moment, but that will be addressed in the next version (see #81).

**Comment by cgfrost** [comment] 2015-07-09 08:33
In the examples folder I can see this happening on files that have the same name as the extension, for example `ico.ico` and svg.svg`. Is that by design as well or a bug? I suspect that it shouldn't happen in that case.

**Comment by ivogabe** [comment] 2015-07-10 07:37
@cgfrost I agree that that isn't desired, I'll try to filter these out.

**Comment by ivogabe** [comment] 2015-07-11 09:21
@cgfrost Solved in 7efcb3893c677ed096dfded5e36245690da03b42

**Comment by ivogabe** [comment] 2015-07-12 06:23
The next version has an option to hide secondary icons (#86) and fixes formatting (#81).

**Closed by ivogabe** 2015-07-12 06:23 UTC
